### ISSUE TITLE
Can i resize the exported component?

### ISSUE THREAD

**Issue by ahwanfebriantoro** [salman-monetate/react-component-export-image#10]
I think the resolution of the components I export is too small. Is there an option to increase or decrease the image resolution?

**Comment by ahwanfebriantoro** [comment]
well, i resolve this by by adding scale option on html2canvas argument

**Comment by salman-monetate** [comment]
Will add something in the future to pass `html2canvas` option.

**Comment by DevCraftsmanShubham** [comment]
> html2canvas

can you send me a code sample how did you achieved  that?

**Comment by drexkooo** [comment]
bump. For now I'm going to duplicate my component (1 small one displayed on screen, other large one hidden behind with z-index), and export the large one. @sk1794 i think he meant using the "transform: scale()" css property.
