### ISSUE TITLE
react-component-export-image does not export SVG element, also it has problems with arabic langauge?

### ISSUE THREAD

**Issue by aliplutus** [salman-monetate/react-component-export-image#15]
react-component-export-image does not export SVG element, also it has problems with arabic langauge?

**Comment by nikolaynikolaevn** [comment]
I am also experiencing a problem with exporting some SVGs.

**Comment by salman-monetate** [comment]
`react-component-export-image` uses `html2Canvas`, this issue is open there

https://github.com/niklasvh/html2canvas/issues/1543

**Comment by aliplutus** [comment]
is their a way to export components as images without blugins?

**Comment by salman-monetate** [comment]
I don't know your use case but, you can have a look at 

https://developers.google.com/web/tools/puppeteer/examples

**Comment by salman-monetate** [comment]
I have added options fields to pass it to `html2canvas`, @aliplutus does that help in solving the issue?
