### ISSUE TITLE
Elements are cropped out (partially missing) in exported images (React production build)

### ISSUE THREAD

**Issue by nikolaynikolaevn** [salman-monetate/react-component-export-image#16]
This happens with exporting components that contain SVGs. Every time an export is started the cropped out (partially missing) regions are different even though the content stays completely the same.

**Comment by salman-monetate** [comment]
Also if you can create a jsfiddle, it would help. Thanks for using `react-component-export-image`

`react-component-export-image` uses `html2Canvas`, this issue is open there

https://github.com/niklasvh/html2canvas/issues/1543

Also in one of the comments it says if you add width and height to the svg it works, can you please try and let me know. If it still doesn't work, can look for the alternative.

**Comment by nikolaynikolaevn** [comment]
@salman-monetate Thank you, adding width and height worked in my case.

**Comment by nikolaynikolaevn** [comment]
Actually I was referring to another issue with my earlier reply. The issue with the missing image was fixed but the cropping issue is still present. What I currently found is that the issue does not occur for a development build of React but occurs for a production build.

I am using _recharts_ and _antd_ components in the export component in the first example.
The second example is using only a Table component from antd.

So this does not seem to be an issue with _recharts_.

The code is similar to the one below:

Case 1:

  ```
const ExportableChart = React.forwardRef((props, ref) => {
    return (
      <div>
        <Button onClick={() => exportComponentAsPNG(componentRef, generateGraphExportFileName())}>
          Download
        </Button>
        <div style={{ backgroundColor: '#FBFBFB', padding: 20 }} ref={ref}>
          {chartData.length > 0 ?
            <div>
              <div style={{display: "flex", justifyContent: "center", marginTop: "10px"}}>Test</div>
                <div style={{
                  paddingBottom: '27%', /* 16:9 */
                  position: 'relative',
                  height: 0,
                  minWidth: '200px',
                  minHeight: '270px'
                }}>
                  <div style={{
                    position: 'absolute',
                    top: '0',
                    left: '0',
                    width: '95%',
                    height: '95%'
                  }}>
                    <ResponsiveContainer style={{ width: '100%', height: '100%' }}>
                      <LineChart
                        data={chartData}
                        margin={{
                          top: 5, right: 30, left: 20, bottom: 5,
                        }}
                      >
                        <CartesianGrid strokeDasharray="3 3" />
                        {shouldTimeScaleXAxisTicks ? 
                        <XAxis minTickGap={500} type="number" scale="time" domain={["dataMin", "dataMax"]} dataKey="date" ticks={uniqueDate.length > 0 && uniqueDate[0].date} tick={<CustomizedAxisTick />}/>
                        :
                        <XAxis dataKey="date" ticks={uniqueDate.length > 0 && uniqueDate} />
                        }
                        <YAxis />} />
                        <Tooltip />} />
                        <Line />
                      </LineChart>
                    </ResponsiveContainer>
                  </div>
                </div>
            </div>
            : <Empty />
          }
        </div>
      </div>
    );
  });
```

Case 2:

```
const ExportableTable = React.forwardRef((props, ref) => {
  return (
    <div ref={ref}>
      <div style={{display: "grid", justifyContent: "center"}}>
        <data-heading>Test</data-heading>
      </div>
      <Table columns={expandedColumns}
        pagination={{
          hideOnSinglePage: true
        }}
        dataSource={props.userData} />
    </div>
  );
});
```

**Comment by nikolaynikolaevn** [comment]
P.S. I am using react-component-export-image 0.1.7 and the issue also occurs for PDF export.

**Comment by nikolaynikolaevn** [comment]
@salman-monetate Please let me know if there is some progress on this item.

**Comment by salman-monetate** [comment]
`html2Canvas` is used to get the png data and then `jspdf` converts it into pdf format. I tried using your example but there are lot of unknown components in it. If you can please provide a bare minimum example with fiddle would be great.

**Comment by nikolaynikolaevn** [comment]
At https://codesandbox.io/s/loving-voice-788jx?file=/src/App.js the JPG export does not work for me.

![component](https://user-images.githubusercontent.com/50246663/95857637-92758c80-0d64-11eb-9722-12162f46cf06.jpeg)

**Comment by nikolaynikolaevn** [comment]
I think the issue is related to `html2Canvas`. I could not reproduce it in a sandbox. The cut happens at random places and always from the top side.

https://github.com/niklasvh/html2canvas/issues/2386

In my case it looks similar to this one: https://github.com/niklasvh/html2canvas/issues/2264

**Comment by nikolaynikolaevn** [comment]
![изображение](https://user-images.githubusercontent.com/50246663/95872356-6283b480-0d77-11eb-834e-41a72661a383.png)

It seems that the canvas gets moved away (in this case to the top).

**Comment by salman-monetate** [comment]
@nikolaynikolaevn above two `html2canvas` issues needs to be fixed for this.

**Comment by nikolaynikolaevn** [comment]
@salman-monetate I understand but can specify the export options (http://html2canvas.hertzen.com/configuration/) be used as a workaround to the html2canvas issues? E.g. providing some communication interface to html2canvas to make it possible to specify the options.

**Comment by nikolaynikolaevn** [comment]
Probably using an x, y- offsets, and/or x,y- scrolls may be a workaround.

**Comment by salman-monetate** [comment]
If that would resolve the issue, I can add `options` to the api

`exportComponentAsPNG(node, fileName, backgroundColor, type, options);` which will be merged with other options. 

```
html2canvas(element, {
       ...options
        backgroundColor: backgroundColor,
        scrollY: -window.scrollY,
        useCORS: true,
    });
```

let me know what you think.

**Comment by nikolaynikolaevn** [comment]
I think that would be a good idea as it seems to be the only thing that can be currently done since the issue seems to be with `html2canvas`.

**Comment by salman-monetate** [comment]
Will add that today.

**Comment by salman-monetate** [comment]
Added the pr https://github.com/salman-monetate/react-component-export-image/pull/17 can you review it.

**Comment by nikolaynikolaevn** [comment]
I reviewed it. It seems fine to me.

**Comment by salman-monetate** [comment]
#17 is merged.

**Comment by nikolaynikolaevn** [comment]
@salman-monetate A bit late but I realized that I and others may need to ovewrite the default value for `scrollY: -window.scrollY` so I think that the the spreaded `...options`, should have been below

```
        backgroundColor: backgroundColor,
        scrollY: -window.scrollY,
        useCORS: true
```

in order to make it possible to ovewrite these values.
