### ISSUE TITLE
Export Component as PDF Options

### ISSUE THREAD

**Issue by mechanicMo** [salman-monetate/react-component-export-image#23]
i have a need to be able to manually set the orientation of a pdf (portrait or landscape)
here's a PR i just closed - https://github.com/salman-monetate/react-component-export-image/pull/22

in this pr i made the option for orientation but the use case feels heavy - now that there's already 5 (potentially 6) options being passed to these export functions, can we make them named? e.g (node, filename, etc) => {node, filename, etc} that way to specify any option you don't also have to specify all before it.

happy to work on it with you, let me know.
Thanks!

**Comment by salman-monetate** [comment]
Only thing is we will break the existing usage.

**Comment by mechanicMo** [comment]
Hi Salman, thanks for being so responsive! I recognize that it will be a breaking change. I think if you release it as a major version update and also add an "upgrade" section to the readme, it will be relatively easy. I've just made a new PR, please check it out and let me know your thoughts. https://github.com/salman-monetate/react-component-export-image/pull/24

what are x & y for? after you let me know i will:
- update the readme
- update the types file
- update the logic in index file to utilize x & y 

again, i know this will be a breaking change, but i think if you release it as a "major version upgrade" then no one will accidentally upgrade to the breaking version. i've added the upgrade notes to the readme. 

if you feel this way is unnecessary, no worries - just let me know and i'll switch it to normal params, but the pdf options can remain.

thanks again !

**Comment by salman-monetate** [comment]
Thanks for your contribution. I have added comments to the pr.
https://artskydj.github.io/jsPDF/docs/module-addImage.html x and y will solve this issue in particular

https://github.com/salman-monetate/react-component-export-image/issues/19

Ok, we will update it as a major version update with breaking change.
but how about having these 4 parameters, we can even drop fileName?
node, fileName = 'component.pdf', html2CanvasOptions = null, pdfOptions = null

**Comment by mechanicMo** [comment]
Hey Salman

I reviewed your comments and pushed new commits. I think that having (node, {filename, options, options}) makes the most sense because to pass pdfoptions you don't have to pass the other values. i think filename is a useful modifier.

what do you think?

**Comment by salman-monetate** [comment]
I agree, this will make it future proof. Most likely will not need any additional parameters.

**Comment by mechanicMo** [comment]
updating the PR again with more structure changes
