### ISSUE TITLE
JPEG method return PNG format data

### ISSUE THREAD

**Issue by sharifme04** [salman-monetate/react-component-export-image#29]
Hi if I write  `exportComponentAsJPEG(componentRef,{fileName: "airplane"})` , it does not return jpg format, its also return a png. but if i do not give `fileName` then it return JPG format. Could you please tell me what is the reason ?

**Comment by salman-monetate** [comment]
https://github.com/salman-monetate/react-component-export-image/pull/30

**Comment by sharifme04** [comment]
HI Thank you for your quick response. I saw it and it looks fine. 👍
