### ISSUE TITLE
Failed to compile ',' expected.

### ISSUE THREAD

**Issue by vinibiso** [salman-monetate/react-component-export-image#31]
Trying to use the lib with typescript and I get a failed to compile error.

<img width="1058" alt="Screen Shot 2020-12-02 at 19 48 34" src="https://user-images.githubusercontent.com/1559421/100940894-880b7f80-34d7-11eb-96c9-e7f1b6b4cce0.png">

Any ideas?
I checked the file and it seems fine.

**Comment by salman-monetate** [comment]
@mechanicMo can you please check this?

**Comment by salman-monetate** [comment]
@vinibiso seems to compiling properly here

https://codesandbox.io/s/react-typescript-forked-oep4y

**Comment by mechanicMo** [comment]
@salman-monetate there's no compilation errors visible on my end either. 

@vinibiso, are you using the latest version of this package?

**Comment by vinibiso** [comment]
Right. It weird. Because it doesn't seem to be anything wrong with the file that it is pointing to.

As to the version. Im using 1.0.4. Is that the correct one?

Could it be my typescript version?

![Screen Shot 2020-12-03 at 17 43 40](https://user-images.githubusercontent.com/1559421/101086071-17c03500-358f-11eb-864d-3e542a53ee5d.png)

**Comment by salman-monetate** [comment]
Yes, `1.0.4` is the latest version. I switched to your version of typescript but still it is working.

**Comment by SigholmErika** [comment]
I get the same problem with typescript (',' expected.  TS1005)

**Comment by koviser** [comment]
The same issue for me with typescript

**Comment by salman-monetate** [comment]
Can any of you share the tsconfig? Also appreciate if you can create or edit a [codesandbox](https://codesandbox.io/s/react-typescript-forked-oep4y).

**Comment by salman-monetate** [comment]
@vinibiso, what is your node version?

**Comment by vinibiso** [comment]
As for the codesandbox, there isn't much, I really just imported the exportComponentAsJPEG function.

Node version is 12.18.0

**Comment by SigholmErika** [comment]
In contrary to vinibiso, I only imported the exportComponentAsJPEG after installing 
Node version: v12.18.4
My config:
```
{
  "compilerOptions": {
    "baseUrl": "src",
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext", "ES6"],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "noImplicitAny": true,
    "noImplicitThis": true,
    "strictNullChecks": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "preserve"
  },
  "include": ["src"]
}

```

**Comment by koviser** [comment]
I've prepared fix for a file, tried to prepare a PR with the separate branch but I don't have permission to do it.
That how I refactor the file for TS, and it's working, @salman-monetate please look into it, and if it's possible just add to the code:
`
declare module 'react-component-export-image' {
    import { Options } from 'html2canvas';
    import { RefObject, ReactInstance } from 'react';

    type PDFOptions = {
        x: number;
        y: number;
        w: number;
        h: number;
        unit: "pt" | "mm" | "cm" | "m" | "in" | "px";
        orientation: 'l' | 'p';
        pdfFormat: string | Array<number>;
    }

    type Params = {
      fileName?: string,
      html2CanvasOptions?: Partial<Options>,
      pdfOptions?: Partial<PDFOptions>,
    }

    type ExportComponentReturn = Promise<(canvas: HTMLCanvasElement) => void>;

    export function exportComponentAsJPEG(
      node: RefObject<ReactInstance>,
      params?: Params
    ): ExportComponentReturn;

    export function exportComponentAsPDF(
      node: RefObject<ReactInstance>,
      params?: Params
    ): ExportComponentReturn;

    export function exportComponentAsPNG(
      node: RefObject<ReactInstance>,
      params?: Params
    ): ExportComponentReturn;
}

`
