### ISSUE TITLE
Created Image has a padding at left

### ISSUE THREAD

**Issue by hmirfh** [salman-monetate/react-component-export-image#36]
When exporting a component to an image, the generated image has white padding in the left side.
I have tried the sample code in the home page with changing the background colour of the ComponentToPrint and it's happening in that as well.
So I'm sure that my project's css is not causing the padding.
Would you please let me know if there is any trick to fix it?

**Comment by salman-monetate** [comment]
Please look into the 

https://html2canvas.hertzen.com/configuration

You can pass html2CanvasOptions inside the second parameter object to control different properties.

**Comment by hmirfh** [comment]
Thanks, Salman,
Appreciate your reply. I used the options parameter and the only thing that was a bit helpful for this issue was extending width.
Now I have the white space on the left and right of the image equally. Would you mind let me know any recommendation of using any property to fix the padding-left for me?
Thanks again

**Comment by salman-monetate** [comment]
```
width | Element width | The width of the canvas
height | Element height | The height of the canvas
x | Element x-offset | Crop canvas x-coordinate
y | Element y-offset | Crop canvas y-coordinate
scrollX | Element scrollX | The x-scroll position to used when rendering element, (for example if the Element uses position: fixed)
scrollY | Element scrollY | The y-scroll position to used when rendering element, (for example if the Element uses position: fixed)
windowWidth | Window.innerWidth | Window width to use when rendering Element, which may affect things like Media queries
windowHeight | Window.innerHeight | Window height to use when rendering Element, which may affect things like Media queries
```

**Comment by hmirfh** [comment]
> Try the following options, also you can do it with styling on the container element.
> 
> ```
> width | Element width | The width of the canvas
> height | Element height | The height of the canvas
> x | Element x-offset | Crop canvas x-coordinate
> y | Element y-offset | Crop canvas y-coordinate
> scrollX | Element scrollX | The x-scroll position to used when rendering element, (for example if the Element uses position: fixed)
> scrollY | Element scrollY | The y-scroll position to used when rendering element, (for example if the Element uses position: fixed)
> windowWidth | Window.innerWidth | Window width to use when rendering Element, which may affect things like Media queries
> windowHeight | Window.innerHeight | Window height to use when rendering Element, which may affect things like Media queries
> ```

**Comment by MehbubRashid** [comment]
@hmirfh did you solve it? i am facing the same issue.it very weird..

**Comment by MehbubRashid** [comment]
Alright finally solved by setting the second argument as 
`var params = {
        html2CanvasOptions: {
            scrollX: -window.scrollX,
            scrollY: -window.scrollY,
            windowWidth: document.documentElement.offsetWidth,
            windowHeight: document.documentElement.offsetHeight
        }
    };`
