### ISSUE TITLE
Font family is changing after export to PDF or PNG

### ISSUE THREAD

**Issue by cristihandev** [salman-monetate/react-component-export-image#37]
I'm Using the Roboto Font and when i exported to PDF or PNG the font suddenly change.

**Component**
![image](https://user-images.githubusercontent.com/27317978/102945594-329a1100-448c-11eb-94ce-a9222d2a248c.png)

**Exported File**
![image](https://user-images.githubusercontent.com/27317978/102945631-5e1cfb80-448c-11eb-9cce-d8c0d5001ca3.png)

**Comment by salman-monetate** [comment]
I think that is an issue with the chart, not this library. Legend and headers are fine.
