### ISSUE TITLE
Map inside iFrame wasn't rendered on the pdf

### ISSUE THREAD

**Issue by top-dev830** [salman-monetate/react-component-export-image#38]
I have map element inside iFrame and I'm going to export this to image or pdf, but it's stripped out.
Please let me know if you have any workaround this.

**Comment by salman-monetate** [comment]
https://leerob.io/blog/how-to-print-in-react-using-iframes

**Comment by top-dev830** [comment]
Thanks for your reply. Salman.

There are several other components I want to get image using this library.
So with this library, can't we print iframe?

**Comment by salman-monetate** [comment]
iframe has its own document context and is not part of the main page. Internally this library uses html2Canvas which traverses the DOM of the page where it is mounted. It collects information on all the elements in the page and then creates a page representation. This means that it does not simply take a page screenshot, but creates a display based on the DOM's assets.

Reference:
https://html2canvas.hertzen.com/documentation.html
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe

**Comment by top-dev830** [comment]
Okay, Thank you for your clarification.

I could be able to handle this.
I was using Looker map and I could get Blob data from looker side directly.
