### ISSUE TITLE
Get generated file

### ISSUE THREAD

**Issue by nikitashum** [salman-monetate/react-component-export-image#4]
Is it possible to pass generated pdf file inside the code without just displaying it in browser?

**Comment by salman-monetate** [comment]
Need to add the functionality for returning the `uri`, even if we add that it will be additional api

**Comment by salman-monetate** [comment]
That is the browser behavior and wouldn't be able to change that.

**Comment by mrsaleh** [comment]
Is it possible to get the generated file now? like a dataurl or blob?

**Comment by salman-monetate** [comment]
You could use html2Canvas directly.
