### ISSUE TITLE
Async functions do not return promise

### ISSUE THREAD

**Issue by ZeMunchkin** [salman-monetate/react-component-export-image#6]
The functions `exportComponentAsPNG`, `exportComponentAsJPEG`, and `exportComponentAsPDF` all call an async function, however they do not return the promise. This makes it difficult to have additional functionality or error handling happen after any of the exported functions are called.

Promise is returned in `exportComponent`, the function used by all three: https://github.com/salman-monetate/react-component-export-image/blob/c188235aa0e1c70a3e3921b17b1bf83090538b9e/index.js#L34-L36

Promise is not returned where used: https://github.com/salman-monetate/react-component-export-image/blob/c188235aa0e1c70a3e3921b17b1bf83090538b9e/index.js#L58-L60

**Comment by salman-monetate** [comment]
Resolved in https://github.com/salman-monetate/react-component-export-image/pull/8
